import test from 'node:test';
import assert from 'node:assert/strict';
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:5173';
if(new URL(origin).hostname!=='127.0.0.1')throw Error('Integration tests are local-only.');
const headers={'Content-Type':'application/json',origin,cookie:'__sites_local_auth=1'};
const get=async()=>{const r=await fetch(origin+'/api/ledger',{headers});assert.equal(r.status,200);return r.json();};
const post=async(body,revision)=>fetch(origin+'/api/ledger',{method:'POST',headers,body:JSON.stringify({...body,revision:revision??(await get()).revision})});
const ok=async body=>{const r=await post(body);assert.equal(r.status,200,await r.text());};
test('full API flow, validation, auth, CSRF, concurrent sales and historical persistence',async()=>{
 assert.equal((await fetch(origin+'/api/ledger')).status,401);
 assert.equal((await fetch(origin+'/api/ledger',{method:'POST',headers:{...headers,origin:'https://invalid.example'},body:'{}'})).status,403);
 const id=crypto.randomUUID(),d=(await get()).now;
 await ok({kind:'product',id,name:'API test '+id.slice(0,5),unit:'kg',price:'700',category:'QA'});
 await ok({kind:'purchase',productId:id,date:d,quantity:'10',price:'400'});
 await ok({kind:'purchase',productId:id,date:d,quantity:'10',price:'450'});
 await ok({kind:'sale',productId:id,date:d,quantity:'12',price:'700'});
 let state=await get();let s=state.ledger.sales.find(s=>s.productId===id);assert.equal(s.cost,490000);assert.equal(s.revenue,840000);
 assert.equal((await post({kind:'sale',productId:id,date:d,quantity:'9',price:'700'})).status,400);
 const concurrent=await Promise.all([post({kind:'sale',productId:id,date:d,quantity:'6',price:'700'},state.revision),post({kind:'sale',productId:id,date:d,quantity:'6',price:'700'},state.revision)]);
 assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);
 state=await get();assert.equal(state.ledger.batches.filter(b=>b.productId===id).reduce((n,b)=>n+b.remaining,0),2000);
 await ok({kind:'adjustment',productId:id,quantity:'1.5',reason:'Ручное взвешивание'});
 const eid=crypto.randomUUID();await ok({kind:'expense',id:eid,name:'Тестовый расход',category:'QA',amount:'100.25',date:d,recurring:true});
 state=await get();assert.equal(state.ledger.expenses.find(e=>e.id===eid).amount,10025);assert.equal(state.ledger.adjustments.find(a=>a.productId===id).difference,-500);
 assert.equal((await post({kind:'repeatExpense',id:eid})).status,400);
 await ok({kind:'expense',id:eid,name:'Исправленный расход',category:'QA',amount:'90.50',date:d,recurring:true});
 assert.equal((await get()).ledger.expenses.find(e=>e.id===eid).amount,9050);
 assert.equal((await post({kind:'archive',id})).status,400);
 await ok({kind:'adjustment',productId:id,quantity:'0',reason:'Списание'});await ok({kind:'archive',id});
 assert.equal((await get()).ledger.products.find(p=>p.id===id).archived,true);
});
